[project]
name = "fatura-itau"
version = "0.0.1"
description = "Conversor de faturas do cartão de crédito Itaú em formato PDF para CSV/Excel"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "pdfplumber>=0.11.7",
    "streamlit>=1.48.1",
]
